spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gin
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
server:
  error:
    include-message: always